# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20161205_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='modified',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_address',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_address',
            field=models.CharField(max_length=600),
        ),
        migrations.AddField(
            model_name='user_source',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Source'),
        ),
        migrations.AddField(
            model_name='user_source',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
